name: Deploy to Azure Static Web Apps (Production)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Let the SWA action handle install + build via Oryx (works great with Vite)
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "."          # repo root
          api_location: ""           # no API/backend
          output_location: "dist"    # Vite outputs to 'dist'
          production_branch: "master"
